controller_manager:
  ros__parameters:
    update_rate: 100

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["rear_left_wheel_joint"]
    right_wheel_names: ["rear_right_wheel_joint"]
    wheel_separation: 0.5
    wheel_radius: 0.1
    base_frame_id: base_link
    cmd_vel_timeout: 0.5
    publish_rate: 50.0
    use_stamped_vel: false

    joints:
      - rear_left_wheel_joint
      - rear_right_wheel_joint

    command_interfaces:
      - velocity
      - position

    state_interfaces:
      - velocity
      - position
